WINDOW_WIDTH = 500
WINDOW_HEIGHT = 500
WINDOW_TITLE = "Particle Sim"

FPS = 60
SHOW_FPS = True

GRID_COLS = 25
GRID_ROWS = 25
GRID_PADDING_HORIZONTAL = 5
GRID_PADDING_VERTICAL = 5
GRID_SPACING_HORIZONTAL = 1
GRID_SPACING_VERTICAL = 1

GRID_WIDTH = WINDOW_WIDTH
GRID_HEIGHT = WINDOW_HEIGHT
GRID_OFFSET_HORIZONTAL = 0  # From the window
GRID_OFFSET_VERTICAL = 0  # From the window

PARTICLE_WIDTH = (GRID_WIDTH - GRID_PADDING_HORIZONTAL * 2 - GRID_SPACING_HORIZONTAL * (GRID_COLS - 1)) // GRID_COLS
PARTICLE_HEIGHT = (GRID_HEIGHT - GRID_PADDING_VERTICAL * 2 - GRID_SPACING_VERTICAL * (GRID_ROWS - 1)) // GRID_ROWS
