WINDOW_WIDTH = 600
WINDOW_HEIGHT = 600
WINDOW_TITLE = "Particle Sim"

FPS = 60
SHOW_FPS = True

GRID_COLS = 10
GRID_ROWS = 10
GRID_PADDING_HORIZONTAL = 10
GRID_PADDING_VERTICAL = 10
GRID_SPACING_HORIZONTAL = 10
GRID_SPACING_VERTICAL = 10

GRID_WIDTH = 500
GRID_HEIGHT = 500
GRID_OFFSET_HORIZONTAL = 50  # From the bottom left of window
GRID_OFFSET_VERTICAL = 50  # From the bottom left of window

PARTICLE_WIDTH = (GRID_WIDTH - GRID_PADDING_HORIZONTAL * 2 - GRID_SPACING_HORIZONTAL * (GRID_COLS - 1)) // GRID_COLS
PARTICLE_HEIGHT = (GRID_HEIGHT - GRID_PADDING_VERTICAL * 2 - GRID_SPACING_VERTICAL * (GRID_ROWS - 1)) // GRID_ROWS

PARTICLE_OFFSET_VERTICAL = (GRID_WIDTH - GRID_PADDING_HORIZONTAL * 2 - GRID_COLS * (PARTICLE_WIDTH + GRID_SPACING_HORIZONTAL) + GRID_SPACING_HORIZONTAL) // 2
PARTICLE_OFFSET_HORIZONTAL = (GRID_HEIGHT - GRID_PADDING_VERTICAL * 2 - GRID_ROWS * (PARTICLE_HEIGHT + GRID_SPACING_VERTICAL) + GRID_SPACING_VERTICAL) // 2

MOUSE_SCROLL_SENSITIVITY = 0.2  # Larger means less sensitive

GRAVITATIONAL_FORCES_ENABLED = True
GRAVITY_FORCE_VERTICAL = -10
GRAVITY_FORCE_HORIZONTAL = 0
