# region graphics
WINDOW_WIDTH = 630
WINDOW_HEIGHT = 600
WINDOW_TITLE = "Particle Sim"

FPS = 60
SHOW_FPS = True

UI_BORDER_COLOUR = (200, 200, 200)

GRID_COLS = 10
GRID_ROWS = GRID_COLS
GRID_PADDING_HORIZONTAL = 10
GRID_PADDING_VERTICAL = 10
GRID_SPACING_HORIZONTAL = 10
GRID_SPACING_VERTICAL = 10

GRID_WIDTH = 500
GRID_HEIGHT = 500
GRID_OFFSET_HORIZONTAL = 50  # From the bottom left of window
GRID_OFFSET_VERTICAL = 50  # From the bottom left of window

PARTICLE_WIDTH = (GRID_WIDTH - GRID_PADDING_HORIZONTAL * 2 - GRID_SPACING_HORIZONTAL * (GRID_COLS - 1)) // GRID_COLS
PARTICLE_HEIGHT = (GRID_HEIGHT - GRID_PADDING_VERTICAL * 2 - GRID_SPACING_VERTICAL * (GRID_ROWS - 1)) // GRID_ROWS

PARTICLE_OFFSET_VERTICAL = (GRID_WIDTH - GRID_PADDING_HORIZONTAL * 2 - GRID_COLS * (PARTICLE_WIDTH + GRID_SPACING_HORIZONTAL) + GRID_SPACING_HORIZONTAL) // 2
PARTICLE_OFFSET_HORIZONTAL = (GRID_HEIGHT - GRID_PADDING_VERTICAL * 2 - GRID_ROWS * (PARTICLE_HEIGHT + GRID_SPACING_VERTICAL) + GRID_SPACING_VERTICAL) // 2

PARTICLE_SELECTION_MENU_PARTICLE_WIDTH = 30
PARTICLE_SELECTION_MENU_PARTICLE_HEIGHT = PARTICLE_SELECTION_MENU_PARTICLE_WIDTH

PARTICLE_SELECTION_MENU_OFFSET_VERTICAL = GRID_OFFSET_VERTICAL
PARTICLE_SELECTION_MENU_OFFSET_HORIZONTAL = 10
PARTICLE_SELECTION_MENU_POSITION_HORIZONTAL = GRID_OFFSET_HORIZONTAL + GRID_WIDTH + PARTICLE_SELECTION_MENU_OFFSET_HORIZONTAL
PARTICLE_SELECTION_MENU_POSITION_VERTICAL = PARTICLE_SELECTION_MENU_OFFSET_VERTICAL
PARTICLE_SELECTION_MENU_PADDING_HORIZONTAL = 10
PARTICLE_SELECTION_MENU_PADDING_VERTICAL = PARTICLE_SELECTION_MENU_PADDING_HORIZONTAL
PARTICLE_SELECTION_MENU_WIDTH = PARTICLE_SELECTION_MENU_PARTICLE_WIDTH + 2 * PARTICLE_SELECTION_MENU_PADDING_HORIZONTAL
PARTICLE_SELECTION_MENU_HEIGHT = GRID_HEIGHT
# endregion

# region ui
PARTICLE_SELECTION_MENU_SCROLL_SENSITIVITY = 0.2  # Larger means less sensitive

SCROLL_FOR_PARTICLE_MENU_ANYWHERE = True
# endregion

# region physics
GRAVITATIONAL_FORCES_ENABLED = True
GRAVITY_FORCE_VERTICAL = -10
GRAVITY_FORCE_HORIZONTAL = 0
# endregion
